# Generated by Django 4.2.4 on 2023-11-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_joinform_material_delete_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinform",
            name="course",
            field=models.CharField(
                choices=[("bcom", "Bcom"), ("biology", "Biology"), ("ai", "Ai")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="joinform",
            name="department",
            field=models.CharField(
                choices=[
                    ("commerce", "Commerce"),
                    ("science", "Science"),
                    ("computerscience", "Computerscience"),
                ],
                max_length=50,
            ),
        ),
    ]
